* Opis programu
  Program składa się z dwóch części:
  - Sprawdzanie poprawności kodu
  - Generownanie kodów

** Sprawdzanie poprawności kodu
  Okno tej części składa się z:
  - przestrzeni na wpisanie kodu w centralnej części,
  - pola ze znalezionymi sufiksami (pokazywane są również powtórzenia),
  - paska przycisków na górze,
  - paska stanu na dole
    - w tym pasku pokazywane są komunikaty na temat poprawności kodu.

  Program zakłada, że słowa kodowe rozdzielone są dowolną ilością białych
  znaków. Można wprowadzać dowolne znaki, nie tylo 1 i 0.

** Generowanie kodów
  Włączenie generatora odbywa się po kliknięciu "Otwórz generator"
  W pasku głównego okna. Generowanie kodów w zależności od ustawień
  może trwać bardzo długo. Nie da się tego przerwać inaczej niż
  zabicie programu.
  
  Program ma dwa tryby generowanie kodów:
  1. Słowa losowe
  2. Słowa kolejne

  Oraz dwa podtryby:
  1. Usuwaj krótsze,
     W tym trybie przy dwóch słowach kodowych z kodu usuwane jest to krótsze.
  2. Usuwaj dłuższe,
     Usuwa dłuższy z wyrazów.

  Jeśli konflikt powoduje wyraz kodowy z sufiksem usuwane jest słowo kodowe
  niezależnie od wybranej strategii.

*** Słowa losowe
    Program generuje losowe słowa o losowej długości nie przekreczającej 3/4
    ilości słów. Powtarza to tyle razy, ile określone w polu "Ilość testów".

    Na wyjściu użytkownik otrzymuje kolekcję wygenerowanych kodów (pogrupowane
    nawiasami) oraz różne informacje statystyczne:
    - średnią długość wyrazu liczoną ze wszystkich testów
    - odchylenie std. długości wyrazu
    - średni czas jednego testu i jego odchylenie std.
   
*** Słowa kolejne
    Zamiast losować wyrazy brane są wyrazy reprezentujące binarnie kolejne
    liczby kardynalne. Przy każdym powtórzeniu testu z tymi ustawieniami wynik
    będzie taki sam więc tutaj wartość pola "Ilość testów" nie ma znaczenia.
    
