* Opis programu
  Program składa się z dwóch części:
  - Sprawdzanie poprawności kodu
  - Generowanie kodów

  Program należy odpalać z pliku ambcodes.bat.

** Sprawdzanie poprawności kodu
  Okno tej części składa się z:
  - przestrzeni na wpisanie kodu w centralnej części,
  - pola ze znalezionymi sufiksami (pokazywane są również powtórzenia),
  - paska przycisków na górze,
  - paska stanu na dole
    - w tym pasku pokazywane są komunikaty na temat poprawności kodu.

  Program zakłada, że słowa kodowe rozdzielone są dowolną ilością białych
  znaków. Można wprowadzać dowolne znaki, nie tylko 1 i 0.

** Generowanie kodów
   Włączenie generatora odbywa się po kliknięciu "Otwórz generator"
   W pasku głównego okna. Generowanie kodów w zależności od ustawień
   może trwać bardzo długo. Nie da się tego przerwać inaczej niż
   zabicie programu.
  
   Program ma dwa tryby generowania kodów:
   1. Słowa losowe
   2. Słowa kolejne
     
   Oraz dwa pod-tryby:
   1. Usuwaj krótsze,
      w tym trybie przy dwóch słowach kodowych z kodu usuwane jest to krótsze.
   2. Usuwaj dłuższe,
      usuwa dłuższy z wyrazów.

   Jeśli konflikt powoduje wyraz kodowy z sufiksem usuwane jest słowo kodowe
   niezależnie od wybranej strategii.

*** Słowa losowe
    Program generuje losowe słowa o losowej długości nie przekraczającej ilości
    wyrazów jeśli ilość jest mniejsza od 10. Powyżej 9 wyrazów wyrazy mają
    długość nie przekraczającą 3/4 ilości. Powtarza test tyle razy, ile
    określone w polu "Ilość testów".

    Na wyjściu użytkownik otrzymuje kolekcję wygenerowanych kodów (pogrupowane
    nawiasami) oraz różne informacje statystyczne:
    - średnią długość wyrazu liczoną ze wszystkich testów
    - odchylenie std. długości wyrazu
    - średni czas jednego testu i jego odchylenie std.
   
*** Słowa kolejne
    Zamiast losować wyrazy brane są wyrazy reprezentujące binarnie kolejne
    liczby kardynalne. Przy każdym powtórzeniu testu z tymi ustawieniami wynik
    będzie taki sam więc tutaj wartość pola "Ilość testów" jest ignorowana
    i test wykonywany jest tylko raz.

* Strategia generowania kodów.
  Lepszą strategia usuwania wyrazów niepasujących jest taka, w której
  usuwamy krótsze wyrazy ponieważ zwalniamy większą grupę prefiksów
  niż gdy usuwamy dłuższe.

  Najłatwiej potwierdzić to używając testu z wyrazami kolejnymi.
  Średnie długości wyrazów i ich odchylenia std. dla kodu 40-wyrazowego
  i strategii:
  - *dłuższe*: 6.0, 1.47
  - *krótsze*: 5.78, 1.25

  Przy strategii *krótsze* otrzymujemy średnio krótszy kod z mniejszym
  rozrzutem długości.
    
